# 配置多个环境，如测试环境（application-dev.yaml）、生产环境（application-prod.yaml）、主配置文件（application.yaml）
# 指定环境：
# 方式1：在 application.yaml 中，指定当前活动的配置文件为 application-dev.yaml
# 方式2：在 Run/Debug Configuration 中，Active profiles 或 Override parameters
#       Active profiles 只可用于指定要使用的环境，如，注解填写 prod，表示在生产环境下
#       Override parameters 命令行参数配置环境变量，如，spring.profiles.active=dev，表示测试环境下
spring:
  profiles:
    active: dev